const body = document.querySelector("body");
const p = document.createElement("p");
const textNode_1 = document.createTextNode("Hola Text Node 1");
const textNode_2 = document.createTextNode("Hola Text Node 2");
console.log(p.isConnected);
p.appendChild(textNode_1);
p.appendChild(textNode_2);
console.log(p.isConnected);
console.log(p);
console.log(p.textContent);
body.appendChild(p);
console.log(p.childNodes[0]);
console.log(p.childNodes[1]);
console.log(p.isConnected);
